croct-tech/cli

.eslintrc.cjs
package-lock.json
package.json
src/application/project/code/transformation/javascript/javaScriptCodemod.ts
src/application/project/code/transformation/javascript/jsxWrapperCodemod.ts
src/application/project/code/transformation/javascript/nextJsMiddlewareCodemod.ts
src/application/project/code/transformation/javascript/parseNextJsConfig.ts
src/application/project/code/transformation/javascript/utils/addImport.ts
src/application/project/code/transformation/javascript/utils/addReexport.ts
src/application/project/code/transformation/javascript/utils/babel.ts
src/application/project/code/transformation/javascript/utils/getExportedNames.ts
src/application/project/code/transformation/javascript/utils/getImportLocalName.ts
src/application/project/code/transformation/javascript/utils/hasImport.ts
src/application/project/code/transformation/javascript/utils/hasReexport.ts
src/application/project/code/transformation/javascript/utils/transformImports.ts
src/application/project/sdk/javasScriptSdk.ts
src/infrastructure/application/cli/io/formatting.ts
tsconfig.build.json
tsup.config.ts

Migrate to ESM

---

src/application/cli/form/page.ts
src/application/project/sdk/javasScriptSdk.ts

Add dependency

---

.github/workflows/deploy-published-releases.yaml
.github/workflows/publish-pr-preview.yaml
src/infrastructure/application/cli/program.ts

Use the package.json version instead of the hard-coded version in the command.

Fix version command

---

src/application/api/workspace.ts
src/application/cli/command/template/create.ts
src/application/cli/io/logFormatter.ts
src/application/cli/io/output.ts
src/application/template/action/locateFileAction.ts
src/application/template/action/printAction.ts
src/application/template/resourceMatcher.ts
src/infrastructure/application/api/graphql/workspace.ts
src/infrastructure/application/cli/io/consoleOutput.ts
src/infrastructure/application/cli/io/formatting.ts
src/infrastructure/application/cli/io/interactiveTaskMonitor.ts
src/infrastructure/application/cli/io/nonInteractiveTaskMonitor.ts
src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
src/infrastructure/application/validation/actions/locateFileOptionsValidator.ts
src/infrastructure/application/validation/actions/printOptionsValidator.ts
src/infrastructure/application/validation/actions/promptOptionsValidator.ts
src/infrastructure/application/validation/croctConfigurationValidator.ts
src/infrastructure/application/validation/zodValidator.ts

This PR fixes minor issues like typos, validation, etc.

Fix minor issues

---

src/infrastructure/application/evaluation/jsepExpressionEvaluator.ts

This PR fixes cases where values were returned before being fully resolved. For example, calling `[a, b, c].join('/')` would incorrectly join unresolved promises because the array was not fully resolved before invoking the `join` method.
It also fixes the behavior of the nullish coalescing operator (`??`), which previously threw an error when accessing an undefined property instead of returning the right-hand side as expected.

Fix eveluation

---

src/application/cli/command/init.ts

This PR removes the slot selection from initialization to streamline the process.

Remove slot selection from initialization

---

src/application/template/resourceRefactor.ts

Currently, when a component ID is renamed due to a conflict, references to that component in other schemas are not updated. This leads to broken content, as those references end up pointing toa unrelated component, causing the CLI to report content errors.
This PR fixes the issue by traversing all schemas and updating references to reflect the new component ID.

Fix component refactoring

---

src/infrastructure/application/evaluation/jsepExpressionEvaluator.ts

Expose more array methods

---

src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts

This PR will correct the validation for the experiment allocation at the workspace resource creation.

Correct validation at workspace resource creation

---

src/infrastructure/application/cli/cli.ts

Fix action name

---

src/application/template/action/executePackage.ts
src/infrastructure/application/cli/cli.ts

Remove command timeout

---

src/application/template/action/checkDependencyAction.ts
src/infrastructure/application/cli/cli.ts

This PR addresses two issues:
- Fixes the broken logic that checks for dependencies
- Prevents the initialize command from failing when the project is already initialized

Fix action logic

---

src/application/fs/fileSystem.ts
src/application/fs/localFilesystem.ts
src/application/predicate/matchesGitignore.ts
src/application/project/code/transformation/globImportCodemod.ts
src/application/project/sdk/javasScriptSdk.ts
src/application/provider/resource/fileSystemProvider.ts
src/application/template/action/locateFileAction.ts
src/infrastructure/application/cli/cli.ts

This PR introduce several optimization related to file scanning, including:
- Automatic exclusion of paths listes in git ignore
- Centralized logic for exclusion
- More robust filtering support direct in the filesystem

Improve filesystem scanning

---

src/application/project/packageManager/nodePackageManager.ts
src/infrastructure/application/cli/cli.ts

Despite having disabled cache on our CDN, result data continues to be cached for hours.
This PR adds a cache-busting mechanism to force fresh results and ensure data is always up-to-date.

Cache busting

---

src/infrastructure/application/cli/program.ts

This PR fixes a bug in the logic of parsing array arguments.

Fix array argument parsing

---

src/application/project/packageManager/nodePackageManager.ts
src/application/template/action/importAction.ts
src/application/template/action/runAction.ts

This PR add tracing for JSON-related errors.

Improve error reporting

---

package-lock.json
package.json
src/application/template/action/runAction.ts

Fix import

---

src/application/template/action/printAction.ts

Fix the print action message alignment.

Fix message alignment

---

src/application/cli/authentication/authenticator/providedTokenAuthenticator.ts
src/infrastructure/application/cli/cli.ts
src/infrastructure/application/cli/program.ts

This PR adds a new configuration to specify a token issued externally.

Add option to pass external token

---

src/application/project/sdk/javasScriptSdk.ts
src/infrastructure/application/api/graphql/queries/component.ts
src/infrastructure/application/api/graphql/queries/organization.ts
src/infrastructure/application/api/graphql/queries/slot.ts

This PR resolves edge cases where users with access to over 100 organizations or workspaces containing more than 100 slots or components encountered missing items during generation.
It also improves performance by refactoring the type and content generation logic to fetch only the relevant slots instead of the entire list.

Increase component and slot query

---

package-lock.json
package.json
src/application/cli/autoUpdater.ts
src/application/cli/command/welcome.ts
src/application/cli/configuration/provider.ts
src/application/project/packageManager/agent/bunAgent.ts
src/application/project/packageManager/agent/executableAgent.ts
src/application/project/packageManager/agent/noopAgent.ts
src/application/project/packageManager/agent/npmAgent.ts
src/application/project/packageManager/agent/packageManagerAgent.ts
src/application/project/packageManager/agent/pnpmAgent.ts
src/application/project/packageManager/agent/yarnAgent.ts
src/application/project/packageManager/lazyPackageManager.ts
src/application/project/packageManager/nodePackageManager.ts
src/application/project/packageManager/packageManager.ts
src/infrastructure/application/cli/cli.ts
src/infrastructure/application/cli/io/boxenFormatter.ts
src/infrastructure/application/cli/io/formatting.ts
src/infrastructure/application/validation/cliSettingsValidator.ts

This PR adds an auto-updater that checks for new versions every 12 hours and updates the CLI automatically.

Add an auto-updater

---

src/application/template/action/deletePathAction.ts
src/application/template/action/downloadAction.ts
src/application/template/action/replaceFileContentAction.ts
src/application/template/action/resolveImportAction.ts
src/infrastructure/application/cli/cli.ts
src/infrastructure/application/validation/actions/deletePathOptionsValidator.ts
src/infrastructure/application/validation/actions/resolveImportOptionsValidator.ts

This PR introduces two new actions:
* `resolve-import`: Resolves and rewrites import paths.
* `delete-path`: Deletes files and directories.
It also improves error reporting for the following actions:
* `replace-file-content` and `download` now show error messages when no matches are found.

Add new actions

---

src/application/cli/autoUpdater.ts
src/application/cli/io/output.ts
src/application/project/packageManager/agent/executableAgent.ts
src/application/project/packageManager/lazyPackageManager.ts
src/application/project/packageManager/nodePackageManager.ts
src/application/project/packageManager/packageManager.ts
src/application/project/sdk/javasScriptSdk.ts
src/application/project/server/processServer.ts
src/application/project/server/server.ts
src/application/template/action/addDependencyAction.ts
src/application/template/action/installAction.ts
src/application/template/action/startServerAction.ts
src/infrastructure/application/cli/cli.ts
src/infrastructure/application/cli/io/formatting.ts
src/infrastructure/application/cli/io/interactiveTaskMonitor.ts

This PR improves progress reporting for long-running tasks.

Improve progress reporting

---

src/application/cli/autoUpdater.ts
src/application/project/sdk/javasScriptSdk.ts
src/application/template/action/addDependencyAction.ts
src/application/template/action/executePackage.ts
src/application/template/action/installAction.ts
src/application/template/action/startServerAction.ts
src/infrastructure/application/cli/io/taskProgressLogger.ts

This PR extract the logging logic reused across different tasks into a new logger.

Logging logic

---

package-lock.json
package.json
src/application/project/server/processServer.ts
src/application/template/action/executePackage.ts
src/infrastructure/application/cli/cli.ts
src/infrastructure/application/cli/io/consoleInput.ts
src/infrastructure/application/system/nodeProcess.ts

Improve exit cleanup

---

src/application/project/code/transformation/javascript/javaScriptCodemod.ts

Remove wildcard import
