croct-tech/cli

src/application/cli/command/open.ts
Currently, only croct: and croct:/ links are supported. This PR updates the logic to also support croct://, which is the format most softwares (e.g: Slack) and websites expect to recognize a clickable link.
=> Support URL-like deep links

src/infrastructure/application/cli/io/consoleInput.ts
This PR fixes a bug where, for prompts expecting an empty string, the returned value incorrectly contains the label instead of an actual empty string. One example is the prompt shown when opening a deep link, which uses an empty string to indicate the current directory. Due to this bug, the CLI attempts to enter the current directory with the "(current)" suffix (used for presentation purposes). which doesn't exist, causing a crash.
The workaround here is to map the prompt’s internal values to the indices of the available choices, then remap them back to their original values before returning them to the calling function.
For more details, see the associated [bug report](https://github.com/terkelg/prompts/issues/349).
=> Fix selection of falsy values

src/application/project/sdk/javasScriptSdk.ts
This PR fixes an error in the CLI where a function references the `contentEntries` variable despite the actual variable being named `contentMap`.
=> Fix content map generation

src/infrastructure/application/api/graphql/user.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/cli/program.ts, src/infrastructure/cache/tokenCache.ts, src/program.ts
This PR fixes an issue in the CLI's token refresh mechanism, which checks if the token is about to expire so it can refresh it before expiry. 
The problem occurs when a clock skew exists between the server and the user's computer: if the local machine's time is behind the server's, the token appears to be issued "in the future" and is deemed invalid. Consequently, the cache returns `null` for an otherwise valid token, causing subsequent authenticated requests to fail and the CLI to crash – despite the user apparently having just logged in successfully.
To resolve this, the PR introduces a `clockSkewTolerance` parameter that specifies a grace period (in seconds). When verifying token validity, the CLI now accounts for this clock skew tolerance to accommodate minor discrepancies between …
=> Add clock skew tolerance

package-lock.json, package.json, src/application/cli/command/welcome.ts, src/application/system/process/process.ts, src/application/system/protocol/failSafeRegistry.ts, src/application/system/protocol/firefoxRegistry.ts, src/application/system/protocol/linuxRegistry.ts, src/application/system/protocol/macOsRegistry.ts, src/application/system/protocol/multiRegistry.ts, src/application/system/protocol/windowsRegistry.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/system/nodeProcess.ts
This pull request adds a workaround specifically for Firefox on macOS. There is a [known bug](https://bugzilla.mozilla.org/show_bug.cgi?id=718422) in Firefox that prompts users to reselect the application whenever they open a URL. To work around this, we now configure the application within the Firefox profile. 
If Firefox is not installed or the profile directory is unavailable, the process gracefully fails without throwing errors, thanks to the `FailSafeRegistry`.
=> Add Firefox profile workaround on macOS

src/application/cli/form/application/applicationForm.ts
This PR fixes a bug where the application form failed to distinguish between production and development environments during URL validation, causing localhost to be incorrectly rejected.
=> Fix application form

src/application/cli/form/organization/organizationForm.ts
The backend requires specifying a record limit when fetching resources – there's no way to retrieve all of them. To work around this, the CLI uses a high limit (e.g., 100), which works fine for most resources like organizations, since users typically have one or just a few. However, support users can have access to hundreds of applications.
Previously, even when an organization was specified via a parameter, the CLI searched for it within the limited result set, which could fail if it wasn't included. This PR changes the logic so that when an organization is explicitly specified, the CLI fetches it directly, bypassing the limit.
The default behavior – listing organizations for selection – remains limited to the configured maximum.
=> Optimize organization form

src/application/cli/form/organization/organizationForm.ts, src/infrastructure/application/system/command/spawnExecutor.ts
Windows users reported an error when installing NPM dependencies, but the error wasn't visible in the console, making screenshots of the issue unhelpful for debugging.
This PR improves the error reporting so that any underlying errors are properly surfaced in the console, making future issues easier to diagnose.
It also fixes the root cause: on Windows, using spawn with npm without the shell option results in a spawn npm ENOENT error because the system cannot locate the command. By explicitly enabling the shell in the command executor, the error is resolved and the install process works as expected.
=> Fix command executor

src/application/project/sdk/plugNextSdk.ts
This PR fixes a bug where the Next.js SDK failed to resolve the layout file when the project uses a `src` directory. The SDK was incorrectly pointing to the wrong folder when the layout could not be found.
Additionally, it was only checking for `jsx` and `tsx` extensions, ignoring `js` and `ts`. This PR updates the resolution logic to include all relevant extensions: `js`, `ts`, `jsx`, and `tsx`.
=> Fix layout path resolution in Next.js SDK

src/application/cli/command/template/create.ts, src/application/template/action/importAction.ts, src/application/template/template.ts, src/infrastructure/application/cli/program.ts, src/infrastructure/application/validation/templateValidator.ts
This PR renames the `options` property in string options to `choices` to reduce ambiguity. It also makes `title` and `description` required fields for templates. Additionally, it enforces that option names follow the `/^[a-zA-Z0-9_]+$/` pattern to ensure compatibility with terminal command options.
=> Rename options and add default default values to template

src/infrastructure/application/validation/templateValidator.ts
This PR allows hyphens in option names, as long as they are not at the beginning.
=> Allow dash in option names

src/application/template/action/downloadAction.ts, src/infrastructure/application/validation/actions/downloadOptionsValidator.ts
This PR adds support for overriding existing files during download. This is useful in scenarios where overwriting is intentional, such as scaffolding a new project from a template and replacing the default initial page
=> Add support for overriding files

src/application/project/configuration/projectConfiguration.ts, src/application/project/sdk/javasScriptSdk.ts, src/application/project/sdk/lazySdk.ts, src/application/project/sdk/plugJsSdk.ts, src/application/project/sdk/plugNextSdk.ts, src/application/project/sdk/plugReactSdk.ts, src/application/project/sdk/sdk.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/validation/croctConfigurationValidator.ts, src/infrastructure/application/validation/zodValidator.ts
While working on templates, I realized the need for additional configurable paths, such as paths for libraries and source files (e.g., `src`), which are currently not supported in the config file. The issue is that paths are resolved only once during initialization, so introducing new paths later would be a breaking change. At that point, the CLI would either reject the configuration and force re-initialization or assume a default path without verifying the folder exists.
To address this, this PR refactors the path resolution logic to allow all paths in the config file to be optional. It also introduces a new `getPaths` method in the SDK, which encapsulates the logic for resolving folder paths—even after the initial setup.
With this change, projects are no longer required to specify all …
=> Redesign project path resolution

src/application/template/action/downloadAction.ts
This PR adds support for explicitly specifying when files should be overwritten during downloads. Previously, overwriting was disallowed by default to avoid accidental overwriting. However, there is a legitimate scenario for intentional overwriting, such as when initializing a new project where prompting the user isn't necessary.
By default, users will be prompted to confirm overwriting existing files, but this behavior can now be controlled using the overwrite flag. The only exception remains when the destination path exists as a file rather than a folder; in this case, the user will always be prompted, since the existing file must be deleted to create the required folder structure.
=> Add support for overwriting files

src/application/template/action/importAction.ts
This PR sets `null` as the default value for optional options that are not specified. Previously, these values were `undefined`, which could lead to runtime errors when accessing properties like `options.flag`.
As a result, developers had to write verbose expressions such as `options.flag ?? null === null ? "value" : options.flag`, which hurts the developer experience.
With this change, all non-mandatory options default to `null` when not provided, making it easier to check for missing values using simple expressions like `options.flag === null`.
Since all valid option values are non-null by design, this change introduces no ambiguity.
=> Set omitted options to null

src/application/project/sdk/javasScriptSdk.ts
The current resolution logic is always using the first path of the list instead of the default path specified.
=> Fix path resolution logic

src/application/cli/command/open.ts, src/application/cli/command/welcome.ts, src/application/cli/configuration/fileConfigurationStore.ts, src/application/cli/configuration/normalizedConfigurationStore.ts, src/application/cli/configuration/provider.ts, src/application/project/configuration/manager/indexedConfigurationManager.ts, src/application/project/packageManager/agent/executableAgent.ts, src/application/project/server/processServer.ts, src/application/system/executableLocator.ts, src/application/system/process/executor.ts, src/application/system/protocol/linuxRegistry.ts, src/application/system/protocol/macOsRegistry.ts, src/application/system/protocol/windowsRegistry.ts, src/application/template/action/executePackage.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/cli/program.ts, src/infrastructure/application/project/javaScriptFormatter.ts, src/infrastructure/application/system/command/spawnExecutor.ts, src/infrastructure/application/validation/cliSettingsValidator.ts
This PR adds a mechanism to detect when the CLI has been updated and automatically reinstalls deep links. This eliminates the need for manual intervention and prevents issues caused by outdated links after an update.
It also reverts the change from #22 that forced commands to run in shell mode—a workaround that introduced several problems, such as macOS failing to pass multiline arguments. That change was originally made to ensure commands like npm could be resolved on Windows, where global executables aren't always directly accessible.
To solve this properly, the command executor now resolves the full path of the executable by inspecting the system’s PATH and supported extensions. Since Node.js can't spawn .bat and .cmd files directly, those are still run in shell mode.
=> Add auto-update for deep links

src/application/cli/command/welcome.ts
This PR fixes a bug introduced in #35 where the CLI version was only being tracked when not running a deep-link command, whereas it should be tracked in all cases.
=> Restore version tracking

src/application/cli/command/init.ts, src/application/template/action/downloadAction.ts, src/infrastructure/application/validation/actions/downloadOptionsValidator.ts
This PR introduces support for renaming downloaded files and directories by allowing a mapping of original paths to target paths.
Previously, the downloaded files had to match the target paths exactly. This limitation made it difficult to reuse the same source file under different names or extensions—especially when the file contents are the same but the desired output varies depending on the context.
=> Add support for renaming downloaded files

src/infrastructure/application/evaluation/jsepExpressionEvaluator.ts, src/infrastructure/application/validation/templateValidator.ts
Add metadata to the list of allowed properties in templates.
=> Allow metadata in templates

src/application/system/protocol/macOsRegistry.ts, src/infrastructure/application/cli/program.ts
This PR fixes deep links on macOS and relocates the deep-link command under the enable/disable command to improve scalability as new flags are introduced. The command changes from croct deep-link enable to croct enable deep-link.
=> Fix deep links

src/application/api/workspace.ts, src/application/template/resourceMatcher.ts, src/application/template/resourceRefactor.ts, src/application/template/resources.ts, src/infrastructure/application/api/graphql/workspace.ts, src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
This PR fixes the validation of the `create-resources` action.
=> Fix create resource validation

src/application/cli/command/template/use.ts, src/application/provider/resource/npmRegistryProvider.ts, src/application/template/action/importAction.ts
The current NPM resolution logic doesn't account for scoped packages that start with `@`. Since `@` is not a valid character in hostnames, the `URL` object strips it out.
This PR fixes the issue by percent-encoding `@` in the hostname and decoding it during URL resolution.
=> Add support for scoped NPM URLs

src/application/cli/form/organization/organizationForm.ts, src/application/template/action/changeDirectoryAction.ts, src/application/template/action/executePackage.ts, src/application/template/action/importAction.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/cli/io/interactiveTaskMonitor.ts, src/infrastructure/application/system/command/spawnExecutor.ts
This PR improves error handling in the `spawn` executor and the `change-directory` action. The bug described in https://github.com/croct-tech/templates/pull/38 was difficult to diagnose due to several issues:
- The loading log for the template remained active for the entire process, preventing Node from exiting on errors and making it seem like the process was still running.
- The `change-directory` action did not verify whether the target directory existed before attempting to set it.
- As a result, `spawn` failed with a misleading `ENOENT` error. While this typically indicates a missing executable, in this case, it was caused by a non-existent working directory due to entering the wrong path.
- The `spawn` executor also failed to properly check for errors from the `wait` call, allowing …
=> Improve error handling

src/application/project/code/transformation/globImportCodemod.ts
This PR introduces support for the ?/ prefix to explicitly mark relative imports as potentially resolvable within the same folder. Previously, we relied on glob patterns like ?/**/*, which could lead to ambiguous or incorrect matches when importing common filenames (e.g., page.module.css) that exist in multiple locations.
=> Add support for relative import

package-lock.json, package.json, src/application/project/code/transformation/javascript/typeErasureCodemod.ts, src/application/project/code/transformation/javascript/utils/isTypescript.ts, src/application/project/code/transformation/pathBasedCodemod.ts, src/extension.d.ts, src/infrastructure/application/cli/cli.ts, src/modules.d.ts, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript-jsx.tsx, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript-line-comments.ts, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript-multiline-comments.ts, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript-preserve-comment.ts, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript-preserve-multiple-comments.ts, test/application/project/code/transformation/fixtures/ts-type-erasure/typescript.ts, test/application/project/code/transformation/javascript/__snapshots__/typeErasureCodemod.test.ts.snap, test/application/project/code/transformation/javascript/typeErasureCodemod.test.ts, test/application/project/code/transformation/javascript/utils/isTypescript.test.ts
This PR adds support for automatic type erasure in TypeScript files.
Currently, to offer templates that work in both TypeScript and JavaScript, developers must maintain separate versions of each file—one typed, one untyped. This creates significant overhead and increases the maintenance burden, as every update must be mirrored manually.
With this change, when a downloaded file has a `.js` or `.jsx` extension, the `download` action will automatically remove all TypeScript-specific syntax if present, eliminating the need to maintain separate JS versions.
=> Add support for automatic type erasure

src/application/provider/resource/fetchProvider.ts, src/application/provider/resource/multiProvider.ts, src/infrastructure/application/cli/cli.ts
Some customers have experienced rate limits from GitHub due to the number of requests made when executing a template. This update introduces a mirror that first attempts to download files from our CDN, falling back to GitHub only if the files are not cached.
It also adds a retry mechanism that makes up to 3 attempts with a 1-second delay between each.
=> Add mirror

src/application/predicate/executableExists.ts, src/infrastructure/application/cli/cli.ts
Running the CLI in a project without a lock file currently results in a "No package manager found" error. This happens because detection relies on either the `npm_config_user_agent` environment variable or the presence of a lock file—both of which are unavailable before the project is initialized.
This PR introduces a new detection method that checks for the package manager executable to improve reliability in uninitialized projects.
=> Fix package-manage discovery

src/application/provider/resource/multiProvider.ts, src/infrastructure/application/cli/cli.ts
Currently, when requesting a template, any error other than 404 is propagated upstream, preventing fallback to other providers. This PR updates the behavior to also attempt other providers if the error is classified as OTHER.
=> Fix provider logic and improve error reporting

package-lock.json, package.json, src/application/logging/treeLogger.ts, src/application/provider/resource/githubProvider.ts, src/application/template/action/downloadAction.ts, src/infrastructure/application/cli/cli.ts
This PR refactors the GitHub provider to improve file download handling. The previous logic relied on a simple file extension check to decide whether to use the raw endpoint or download and extract an entire archive. The new implementation uses the [Git tree API](https://docs.github.com/en/rest/git/trees) to accurately differentiate between files and folders, enabling direct file downloads without extracting archives.
It also includes two bug fixes:
* Resolves an issue in the Tree logger where parallel executions were incorrectly nested.
* Fixes a bug in the download action where filtered downloads failed due to missing parent directories, as the filter prevented folder creation when the parent didn't match.
=> Improve GitHub provider

src/application/project/sdk/plugNextSdk.ts
This PR updates the logic used by the CLI to detect versions earlier than 13 and install the React SDK instead. It addresses an issue where the NPM `semver` package evaluates `15.0.0 >= 13` as false, while evaluating `12.0.0 <= 13` as true.
=> Fix Next.js version detection

src/application/system/process/executor.ts, src/application/template/action/executePackage.ts, src/infrastructure/application/system/command/spawnExecutor.ts, src/infrastructure/application/validation/actions/executePackageOptionsValidator.ts
Until now, templates that needed to call an external CLI used the `execute-package` action, which abstracted all user interactions—either by providing default answers or selectively prompting only for relevant inputs—while forwarding them to the underlying CLI.
However, some upcoming integration templates require interaction with CLIs whose flows are too complex to wrap, such as those involving login processes. To support these cases, this PR introduces a new `interactions: true` option that allows the external CLI to fully take over the terminal by inheriting `stdin`, `stdout`, and `stderr`. Once the CLI finishes execution, control returns to the template flow.
=> Add support for direct interaction with underlying CLIs

src/application/project/packageManager/nodePackageManager.ts
This PR updates the logic for resolving a package's `package.json` path to correctly mimic Node.js' module resolution behavior. Previously, it assumed that the dependency would always exist directly under the project root's `node_modules` folder. This caused issues when dependencies were hoisted or located in parent directories.
The new implementation climbs up the directory tree to locate the nearest `node_modules/<package>/package.json`, returning the correct path or `null` if not found. This ensures compatibility with monorepos and nested environments.
=> Fix NPM logic to find dependency package

src/application/project/packageManager/agent/executableAgent.ts, src/application/project/packageManager/agent/noopAgent.ts, src/application/project/packageManager/agent/packageManagerAgent.ts, src/application/project/packageManager/lazyPackageManager.ts, src/application/project/packageManager/nodePackageManager.ts, src/application/project/packageManager/packageManager.ts, src/infrastructure/application/cli/cli.ts
This PR exposes the name of the package manager being used. This information is useful for templates that require specific configurations depending on the selected package manager.
It also fixes a bug in the logic for checking version compatibility.
=> Expose package manager information

src/application/template/action/replaceFileContentAction.ts
Replace `replaceAll` with `replace` to ensure compatibility with lookahead patterns, as `replaceAll` can behave inconsistently when used with zero-width assertions.
=> Use replace instead of replaceAll

src/infrastructure/application/cli/cli.ts
In some scenarios, especially when running the CLI in automated workflows, it's necessary to specify the organization, workspace, and application IDs in advance to set up the project without user interaction.
This PR enables that by supporting the environment variables `CROCT_ORGANIZATION`, `CROCT_WORKSPACE`, `CROCT_DEV_APPLICATION`, and `CROCT_PROD_APPLICATION`.
=> Add env vars for initialization

src/application/cli/authentication/authenticator/cachedAuthenticator.ts
This PR fixes an issue where running multiple parallel operations that require authentication caused the CLI to trigger overlapping authentication flows.
The CLI automatically handles authentication when an operation needs it. For example, `croct update` performs several parallel fetches that all require authentication. Previously, each fetch initiated its own authentication process, leading to a chaotic experience with overlapping logs and prompts.
To address this, the authenticator now uses a shared in-flight cache. Parallel authentication attempts will share the same promise, ensuring a single, consistent authentication flow.
=> Fix authentication

src/application/cli/io/screenBuffer.ts, src/application/template/action/executePackage.ts, src/infrastructure/application/validation/actions/executePackageOptionsValidator.ts
This PR adds a new `output` option to the `execute-package` action, allowing the command's output to be captured, useful when subsequent steps in the template depend on that output.
=> Add output option to execute-package action

src/infrastructure/application/cli/io/browserLinkOpener.ts
This PR fixes the link opener, which was incorrectly waiting for the browser to close before proceeding.
=> Fix link opener

src/application/template/action/createResourceAction.ts, src/application/template/resourceRefactor.ts, src/infrastructure/application/api/graphql/workspace.ts, src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
This PR addresses several problems related to resource creation:
* Map validation was incorrectly requiring number keys, which is not supported in JSON.
* Resource renaming did not account for experiment content.
* Experiment ID logic was incorrectly tied to the experience, even though that dependency is not required.
* The experiment ID was being returned as `null`, but it should only be `undefined` or a string.
=> Experiment creation

src/application/cli/command/init.ts, src/application/cli/command/install.ts, src/application/project/configuration/manager/cachedConfigurationManager.ts, src/application/project/configuration/manager/configurationManager.ts, src/application/project/configuration/manager/indexedConfigurationManager.ts, src/application/project/configuration/manager/jsonConfigurationFileManager.ts, src/application/project/configuration/manager/newConfigurationManager.ts, src/application/project/configuration/projectConfiguration.ts, src/application/project/sdk/javasScriptSdk.ts, src/infrastructure/application/cli/cli.ts, src/infrastructure/application/validation/croctConfigurationValidator.ts
This PR adds support for the CLI to load partially defined configurations when running the `croct install` command in `--no-interaction` or `--dnd` modes. It also changes the default registered command to `croct --no-interaction install`.
This update is useful for scenarios like templates, where slots, paths, and other settings can be preconfigured while leaving organization, workspace, and related details to be connected later.
With this new behavior, whenever the CLI requires the full configuration, it will prompt the user to complete it. The CLI can now read these incomplete configurations and use them as defaults for the final setup.
=> Add support for partially defined project configurations

src/application/project/code/transformation/javascript/javaScriptCodemod.ts
Avoid the dynamic import from recast.
=> Avoid dynamic import

package-lock.json, package.json, src/application/project/code/transformation/javascript/javaScriptCodemod.ts, src/infrastructure/application/cli/cli.ts
This PR fixes a known TSUP issue that causes bad imports.
=> Fix imports

src/infrastructure/application/api/graphql/workspace.ts
Previously, an experience would only publish if `draft` was `false`. This PR updates it to publish if `draft` is not strictly `false`.
=> Fix draft flag

src/application/cli/command/apiKey/create.ts
This PR optimizes the API key creation flow to avoid prompting the user for environments that don’t exist.
=> Improve api key flow
